---
- name: Converge
  hosts: all
  become: true

  vars:
    log4shell_args: "-p /var/log --quick"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: r0mdau.log4shell_detector
